# Generated by Django 3.0 on 2019-12-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='client',
            name='is_agent',
            field=models.BooleanField(default=True, verbose_name='Перевозчик'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_povider',
            field=models.BooleanField(default=True, verbose_name='Поставщик'),
        ),
    ]
