# Generated by Django 3.0 on 2019-12-05 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20191205_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.ClientType', verbose_name='Тип клиента'),
        ),
    ]
