# Generated by Django 3.0 on 2019-12-05 15:40

import clients.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20191205_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=clients.models.choices_type_client_active, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.ClientType', verbose_name='Тип клиента'),
        ),
    ]
